using System.Text;
using GumpForge.Core.Models;

namespace GumpForge.Generators;

/// <summary>
/// Generates ClassicAssist Python macro scripts for gump construction.
/// ClassicAssist uses Python scripting with UO-specific helper functions.
/// Output is a .py script that can be loaded as a ClassicAssist macro.
/// </summary>
public class ClassicAssistGenerator : IGumpCodeGenerator
{
    public string TargetName => "ClassicAssist";
    public string FileExtension => ".py";

    public string Generate(GumpDocument doc, GenerationOptions opts)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# ClassicAssist Gump Macro");
        sb.AppendLine($"# Generated by GumpForge Gump Editor");
        sb.AppendLine($"# Class: {opts.ClassName}");
        sb.AppendLine();
        sb.AppendLine("from ClassicAssist.UO.Gumps import *");
        sb.AppendLine();

        // Create gump builder
        sb.AppendLine($"# Gump Definition: {opts.ClassName}");
        sb.AppendLine($"gump = Gump({doc.GumpX}, {doc.GumpY})");
        sb.AppendLine($"gump.Closable = {PyBool(doc.IsClosable)}");
        sb.AppendLine($"gump.Disposable = {PyBool(doc.IsDisposable)}");
        sb.AppendLine($"gump.Movable = {PyBool(doc.IsDraggable)}");
        sb.AppendLine($"gump.Resizable = {PyBool(doc.IsResizable)}");
        sb.AppendLine();

        foreach (var page in doc.Pages.OrderBy(p => p.PageNumber))
        {
            sb.AppendLine($"# --- Page {page.PageNumber} ---");
            sb.AppendLine($"gump.AddPage({page.PageNumber})");

            foreach (var element in page.Elements.SelectMany(GumpDocument.FlattenElement))
            {
                var line = GenerateElement(element, opts.UseHexIds);
                if (line is not null)
                    sb.AppendLine(line);
            }

            sb.AppendLine();
        }

        sb.AppendLine("# Send the gump");
        sb.AppendLine("gump.SendGump()");
        sb.AppendLine();

        // Response handler
        var replyButtons = doc.GetAllElements()
            .OfType<GumpButton>()
            .Where(b => b.ButtonType == GumpButtonType.Reply)
            .ToList();

        if (replyButtons.Count > 0)
        {
            sb.AppendLine("# Response Handler");
            sb.AppendLine("def on_response(button_id, switches, text_entries):");
            foreach (var btn in replyButtons)
            {
                var comment = string.IsNullOrEmpty(btn.Name) ? $"Button {btn.ButtonId}" : btn.Name;
                sb.AppendLine($"    if button_id == {btn.ButtonId}:  # {comment}");
                sb.AppendLine("        pass");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string? GenerateElement(GumpElement element, bool hex)
    {
        return element switch
        {
            GumpBackground bg =>
                $"gump.AddBackground({bg.X}, {bg.Y}, {bg.Width}, {bg.Height}, {Id(bg.GumpId, hex)})",
            GumpImage img when img.Hue != 0 =>
                $"gump.AddImage({img.X}, {img.Y}, {Id(img.GumpId, hex)}, {img.Hue})",
            GumpImage img =>
                $"gump.AddImage({img.X}, {img.Y}, {Id(img.GumpId, hex)})",
            GumpImageTiled tiled =>
                $"gump.AddImageTiled({tiled.X}, {tiled.Y}, {tiled.Width}, {tiled.Height}, {Id(tiled.GumpId, hex)})",
            GumpAlphaRegion alpha =>
                $"gump.AddAlphaRegion({alpha.X}, {alpha.Y}, {alpha.Width}, {alpha.Height})",
            GumpButton btn =>
                $"gump.AddButton({btn.X}, {btn.Y}, {Id(btn.NormalId, hex)}, {Id(btn.PressedId, hex)}, {btn.ButtonId}, {(int)btn.ButtonType}, {btn.Param})",
            GumpCheck chk =>
                $"gump.AddCheck({chk.X}, {chk.Y}, {Id(chk.InactiveId, hex)}, {Id(chk.ActiveId, hex)}, {PyBool(chk.InitialState)}, {chk.SwitchId})",
            GumpRadio radio =>
                $"gump.AddRadio({radio.X}, {radio.Y}, {Id(radio.InactiveId, hex)}, {Id(radio.ActiveId, hex)}, {PyBool(radio.InitialState)}, {radio.SwitchId})",
            GumpLabel label =>
                $"gump.AddLabel({label.X}, {label.Y}, {label.Hue}, \"{EscapeString(label.Text)}\")",
            GumpLabelCropped cropped =>
                $"gump.AddLabelCropped({cropped.X}, {cropped.Y}, {cropped.Width}, {cropped.Height}, {cropped.Hue}, \"{EscapeString(cropped.Text)}\")",
            GumpHtml html =>
                $"gump.AddHtml({html.X}, {html.Y}, {html.Width}, {html.Height}, \"{EscapeString(html.Text)}\", {PyBool(html.HasBackground)}, {PyBool(html.HasScrollbar)})",
            GumpHtmlLocalized loc =>
                $"gump.AddHtmlLocalized({loc.X}, {loc.Y}, {loc.Width}, {loc.Height}, {loc.ClilocId}, {PyBool(loc.HasBackground)}, {PyBool(loc.HasScrollbar)})",
            GumpTextEntry entry =>
                $"gump.AddTextEntry({entry.X}, {entry.Y}, {entry.Width}, {entry.Height}, {entry.Hue}, {entry.EntryId}, \"{EscapeString(entry.InitialText)}\")",
            GumpItem item when item.Hue != 0 =>
                $"gump.AddItem({item.X}, {item.Y}, {Id(item.ItemId, hex)}, {item.Hue})",
            GumpItem item =>
                $"gump.AddItem({item.X}, {item.Y}, {Id(item.ItemId, hex)})",
            GumpTooltip tt =>
                $"gump.AddTooltip({tt.ClilocId})",
            GumpGroup => null,
            _ => $"# Unknown: {element.ElementType}"
        };
    }

    private static string Id(int id, bool hex) => hex ? $"0x{id:X}" : id.ToString();
    private static string PyBool(bool value) => value ? "True" : "False";
    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");
}
