using System.Text;
using GumpForge.Core.Models;

namespace GumpForge.Generators;

/// <summary>
/// Generates Sphere-compatible gump dialog scripts.
/// Sphere uses its own scripting syntax with DIALOG definitions:
///   [DIALOG d_name]
///   resizepic, page, button, text, etc.
/// </summary>
public class SphereGenerator : IGumpCodeGenerator
{
    public string TargetName => "Sphere";
    public string FileExtension => ".scp";

    public string Generate(GumpDocument doc, GenerationOptions opts)
    {
        var sb = new StringBuilder();

        // Dialog definition
        sb.AppendLine($"[DIALOG d_{opts.ClassName.ToLower()}]");
        sb.AppendLine($"// Generated by GumpForge Gump Editor");
        sb.AppendLine($"// Gump position: {doc.GumpX}, {doc.GumpY}");
        sb.AppendLine();
        sb.AppendLine($"setlocation={doc.GumpX},{doc.GumpY}");
        if (!doc.IsClosable) sb.AppendLine("noclose");
        if (!doc.IsDraggable) sb.AppendLine("nomove");
        if (!doc.IsDisposable) sb.AppendLine("nodispose");
        sb.AppendLine();

        foreach (var page in doc.Pages.OrderBy(p => p.PageNumber))
        {
            sb.AppendLine($"page {page.PageNumber}");

            foreach (var element in page.Elements.SelectMany(GumpDocument.FlattenElement))
            {
                var line = GenerateElement(element);
                if (line is not null)
                    sb.AppendLine(line);
            }

            sb.AppendLine();
        }

        sb.AppendLine();

        // Button handler
        var replyButtons = doc.GetAllElements()
            .OfType<GumpButton>()
            .Where(b => b.ButtonType == GumpButtonType.Reply)
            .ToList();

        if (replyButtons.Count > 0)
        {
            sb.AppendLine($"[DIALOG d_{opts.ClassName.ToLower()} BUTTON]");
            foreach (var btn in replyButtons)
            {
                var comment = string.IsNullOrEmpty(btn.Name) ? $"Button {btn.ButtonId}" : btn.Name;
                sb.AppendLine($"ON={btn.ButtonId}  // {comment}");
                sb.AppendLine("  // Handle button press");
                sb.AppendLine();
            }
        }

        // Text handler
        var textEntries = doc.GetAllElements().OfType<GumpTextEntry>().ToList();
        if (textEntries.Count > 0)
        {
            sb.AppendLine($"[DIALOG d_{opts.ClassName.ToLower()} TEXT]");
            foreach (var te in textEntries)
            {
                sb.AppendLine($"ON={te.EntryId}  // {(string.IsNullOrEmpty(te.Name) ? $"Entry {te.EntryId}" : te.Name)}");
                sb.AppendLine("  // <ARGS> contains entered text");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private static string? GenerateElement(GumpElement element)
    {
        return element switch
        {
            GumpBackground bg =>
                $"resizepic {bg.X} {bg.Y} {bg.GumpId} {bg.Width} {bg.Height}",
            GumpImage img when img.Hue != 0 =>
                $"gumppic {img.X} {img.Y} {img.GumpId} hue={img.Hue}",
            GumpImage img =>
                $"gumppic {img.X} {img.Y} {img.GumpId}",
            GumpImageTiled tiled =>
                $"gumppictiled {tiled.X} {tiled.Y} {tiled.Width} {tiled.Height} {tiled.GumpId}",
            GumpButton btn =>
                $"button {btn.X} {btn.Y} {btn.NormalId} {btn.PressedId} 1 0 {btn.ButtonId}",
            GumpCheck chk =>
                $"checkbox {chk.X} {chk.Y} {chk.InactiveId} {chk.ActiveId} {(chk.InitialState ? 1 : 0)} {chk.SwitchId}",
            GumpRadio radio =>
                $"radio {radio.X} {radio.Y} {radio.InactiveId} {radio.ActiveId} {(radio.InitialState ? 1 : 0)} {radio.SwitchId}",
            GumpLabel label =>
                $"text {label.X} {label.Y} {label.Hue} {label.Text}",
            GumpLabelCropped cropped =>
                $"croppedtext {cropped.X} {cropped.Y} {cropped.Width} {cropped.Height} {cropped.Hue} {cropped.Text}",
            GumpHtml html =>
                $"htmlgump {html.X} {html.Y} {html.Width} {html.Height} 0 {(html.HasBackground ? 1 : 0)} {(html.HasScrollbar ? 1 : 0)}",
            GumpHtmlLocalized loc =>
                $"xmfhtmlgump {loc.X} {loc.Y} {loc.Width} {loc.Height} {loc.ClilocId} {(loc.HasBackground ? 1 : 0)} {(loc.HasScrollbar ? 1 : 0)}",
            GumpAlphaRegion alpha =>
                $"checkertrans {alpha.X} {alpha.Y} {alpha.Width} {alpha.Height}",
            GumpTextEntry entry =>
                $"textentry {entry.X} {entry.Y} {entry.Width} {entry.Height} {entry.Hue} {entry.EntryId} {entry.InitialText}",
            GumpItem item when item.Hue != 0 =>
                $"tilepic {item.X} {item.Y} {item.ItemId} hue={item.Hue}",
            GumpItem item =>
                $"tilepic {item.X} {item.Y} {item.ItemId}",
            GumpTooltip tt =>
                $"tooltip {tt.ClilocId}",
            GumpGroup => null,
            _ => $"// Unknown: {element.ElementType}"
        };
    }
}
